services:
  - type: web
    name: cyber-itsm-spn
    runtime: ruby
    buildCommand: "bundle install"
    startCommand: "bundle exec rake db:migrate && bundle exec ruby app.rb -p $PORT -o 0.0.0.0"
    envVars:
      - key: RACK_ENV
        value: production
      - key: RUBY_VERSION
        value: 3.3.0
    disk:
      name: cyber-itsm-data
      mountPath: /opt/render/project/src/db/data
      sizeGB: 1
